### ISSUE TITLE
Installation of Zarb node as Windows service

### ISSUE THREAD

**Issue by Stonica** [zarbchain/zarb-go#225]
As we know most computer users use Windows as their OS and starting the Zarb node manually every time it stops because of many reasons(like restarting Machine) is hard for lazy boys like me. So I recommend to add a setup to ask if Zarb need to be started as Windows service every time windows boot?

**Comment by d4rk5h0t** [comment]
@Stonica  thanks for participating on zarb

right now we don't have installer to do this kind configurations for us and since we have a tightly coupled CLI and daemon we don't see any necessity for this.
but since it might help you running a node easier you can try adding the script below to a bat file and have a shortcut of it on your start up folder as discussed [here](https://www.devdungeon.com/content/windows-run-script-startup)

ps. in future if cli and demon get separated we might add this feature in for daemon

```bat
echo "YOUR_KEYFILE_PASSWORD" | zarb.exe start -k /path/to/key.json -w /path/to/work/dir/
```

**Comment by b00f** [comment]
@Stonica 

There is project similar to `bitcoin-qt` for Zarb: [zarb-qt](https://github.com/b00f/zarb-qt)
Probably we can add `autostart` feature there.

**Comment by b00f** [comment]
@Stonica @d4rk5h0t We can close this issue now. We have GUI application that can easily installed in Windows (with installer)
